nim = input("masukkan nim anda: ")
nama = input("masukkan nama lengkap: ")
kelas = input("masukkan kelas anda: ")
usia = input("masukkan usia anda:")
print ("========================")
print ("IDENTITAS MAHASISWA")
print ("========================")
print ("NIM Mahasiswa :",nim)
print ("nama lengkap :",nama)
print ("kelas saat ini:",kelas)
print ("usia anda :",usia)
print ("=========================")
